[workspace]
resolver = "2"
members = [
    "lowertier",
    "vendor/quinn",
    "vendor/quincy-tun",
]
default-members = ["lowertier"]
exclude = [
    "vendor/boringtun-lowertier",
    "vendor/http_req",
    "vendor/kcp-sys",
    "vendor/quinn-proto",
    "vendor/rust-tun",
    "vendor/service-manager-rs",
    "vendor/thunk/thunk-rs",
    "vendor/tokio-websockets",
    "vendor/windivert-rust/windivert",
    "vendor/windivert-rust/windivert-sys",
]

[patch.crates-io]
quincy-tun = { path = "vendor/quincy-tun" }
quinn = { path = "vendor/quinn" }
quinn-proto = { path = "vendor/quinn-proto" }

[workspace.package]
edition = "2024"
rust-version = "1.95"

[profile.dev]
panic = "unwind"
debug = 2

[profile.release]
panic = "abort"
lto = "fat"
codegen-units = 1
opt-level = 3
strip = "symbols"
debug = 0
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false
