[workspace]
resolver = "2"
members = [
    "lowertier",
    "lowertier-gui/src-tauri",
    "lowertier-web",
    "lowertier-contrib/lowertier-ffi",
    "lowertier-contrib/lowertier-uptime",
    "lowertier-contrib/lowertier-android-jni",
]
default-members = ["lowertier", "lowertier-web"]
exclude = [
    "lowertier-contrib/lowertier-ohrs", # it needs ohrs sdk
    "vendor/boringtun-lowertier",
    "vendor/http_req",
    "vendor/kcp-sys",
    "vendor/rust-tun",
    "vendor/service-manager-rs",
    "vendor/thunk/thunk-rs",
    "vendor/tokio-websockets",
    "vendor/windivert-rust/windivert",
    "vendor/windivert-rust/windivert-sys",
]

[workspace.package]
edition = "2024"
rust-version = "1.95"

[profile.dev]
panic = "unwind"
debug = 2

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
strip = true
