packages:
  - 'lowertier-web/frontend'
  - 'lowertier-web/frontend-lib'
  - 'lowertier-gui'
  - 'tauri-plugin-vpnservice'

overrides:
  minimatch: 10.2.4

allowBuilds:
  esbuild: true
  unrs-resolver: true
  vue-demi: true
