#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
harness="$repo_root/script/colima-throughput/e2e.sh"
builder="$repo_root/script/colima-throughput/build-core.sh"
dockerfile="$repo_root/script/colima-throughput/Dockerfile"
readme="$repo_root/script/colima-throughput/README.md"

test -f "$harness"
test -f "$builder"
test -f "$dockerfile"
test -f "$readme"

grep -q '^set -euo pipefail$' "$harness"
grep -q 'trap cleanup EXIT INT TERM' "$harness"
grep -q 'capture_active_logs' "$harness"
grep -q 'DOCKER_CONTEXT' "$harness"
grep -q 'RESULT_DIR' "$harness"
grep -q 'RAW_GATE_BPS' "$harness"
grep -q 'substrate-status.txt' "$harness"
grep -q 'UNDERLAY_PROTOCOL' "$harness"
grep -q 'NETEM_DELAY' "$harness"
grep -q 'NETEM_JITTER' "$harness"
grep -q 'NETEM_LOSS' "$harness"
grep -q 'NETEM_LOSS_CORRELATION' "$harness"
grep -q 'tc qdisc replace dev eth0 root netem' "$harness"
grep -q 'profile=automatic' "$harness"
! grep -q 'ADAPTERS' "$harness"
! grep -q -- '--interface-adapter' "$harness"
grep -q 'PARALLEL_STREAMS' "$harness"
grep -q 'TCP_STREAMS' "$harness"
grep -q 'raw_tcp_streams=(1)' "$harness"
grep -q 'for streams in "${tcp_streams\[@\]}"' "$harness"
grep -q 'UDP_RATES' "$harness"
grep -q 'ENCRYPTION_ALGORITHM' "$harness"
grep -q -- '--encryption-algorithm' "$harness"
grep -q 'perf_parse_iperf_json' "$harness"
grep -q 'IPERF_BUSY_RETRIES' "$harness"
grep -q 'IPERF_TIMEOUT_SECONDS' "$harness"
grep -q 'timeout "$iperf_timeout_seconds" iperf3' "$harness"
grep -q 'RUN_TCP' "$harness"
grep -q 'RUN_UDP' "$harness"
grep -q 'RUN_CPU_PROBE' "$harness"
grep -q 'the server is busy running a test' "$harness"
grep -q 'workload-errors.tsv' "$harness"
grep -q 'start_iperf_server "$port"' "$harness"
grep -q 'cpu-cores-per-gbit.tsv' "$harness"
grep -q -- '--device /dev/net/tun' "$harness"
grep -q 'LOWTIER_CORE_BINARY' "$harness"
grep -q 'core-binary-sha256.txt' "$harness"
grep -q -- '--pull never' "$harness"
grep -q -- '--cap-add NET_ADMIN' "$harness"
grep -q 'TCP_CONGESTION_CONTROL' "$harness"
grep -q 'LOWTIER_BUILD_CACHE_VOLUME' "$builder"
grep -q 'lowertier-linux-build-cache' "$builder"
grep -q -- '--pull never' "$builder"
grep -q -- '--network none' "$builder"
grep -q -- '--cap-add NET_ADMIN' "$builder"
grep -q 'CARGO_TARGET_DIR=/cache/target' "$builder"
grep -q 'rsync -a --relative' "$builder"
! grep -qE '(^|[[:space:]])target([[:space:]\\]|$)' "$builder"
grep -q 'iperf3' "$dockerfile"
grep -q 'ethtool' "$dockerfile"
grep -q -- '--features tun,quic' "$dockerfile"
grep -q 'substrate' "$readme"
grep -q '10GbE' "$readme"

bash -n "$harness"
bash -n "$builder"
echo "colima throughput static tests passed"
